git:
  repository_name: test
  repository_uri: git@test/test.git
  local_path: /tmp
aws:
  application_name: test
  dev_tools_endpoint: git.elasticbeanstalk.us-east-1.amazonaws.com
  region: us-east-1
  hosted_zone: test.com.
  stacks:
    qa:
      domain: qa.test.com.
      endpoint: https://qa.test.com
      newrelic_application_name: test-QA
      basic_auth:
        username: test_username
        password: test_password
      environments:
        -
          name: test-QA-A
          uri: https://testqaa.com
        -
          name: test-QA-B
          uri: https://testqab.com
    uat:
      domain: uat.test.com.
      endpoint: https://uat.test.com
      newrelic_application_name: test-UAT
      basic_auth:
        username: test_username
        password: test_password
      environments:
        -
          name: test-UAT-A
          uri: https://testuata.com
        -
          name: test-UAT-B
          uri: https://testuatb.com
    live:
      domain: live.test.com.
      endpoint: https://live.test.com
      newrelic_application_name: test
      environments:
        -
          name: test-A
          uri: https://testa.com
        -
          name: test-B
          uri: https://testqb.com
